name: Ping Assignees
description: |
  Ping issues assignees who have not been working on the issue anymore

inputs:
  days_before_warning:
    description: Number of days before posting a comment to ping the user
    required: true
  days_before_unassigning:
    description: Number of days before unassigning after the warning
    required: true
  comment:
    description: The comment message
    required: true
  bot_name:
    description: The name of the GitHub account used to post the comment
    required: true
  token:
    description: A GitHub access token
    required: true

runs:
  using: node12
  main: main.js

branding:
  icon: label
