name: Generate changelog
description: Uses lerna-changelog to generate the changelog from a tag to another

inputs:
  from:
    description: Old tag
  to:
    description: New tag
  filter:
    description: Only consider tags containing this substring

outputs:
  changelog:
    description: The new changelog, formatted as a JSON string

runs:
  using: node20
  main: main.js

branding:
  icon: clock
  color: yellow
