name: Create comment
description: Creates a new comment

inputs:
  issue:
    description: The issue number
    required: true
  comment:
    description: The comment message
    required: true
  token:
    description: A GitHub access token
    required: true

runs:
  using: node16
  main: main.js

branding:
  icon: message-square
  color: red
